import Cocoa
import FlowKeysCore

/// Watches `NSPasteboard` for new copies.
///
/// macOS has no "pasteboard changed" notification, so polling `changeCount`
/// is the supported approach. 0.25s is fast enough that an item is always in
/// history before the user can switch apps and paste.
final class ClipboardWatcher {

    private var timer: Timer?
    private var lastChangeCount: Int
    private let store: ClipboardStore
    /// Consulted so a paste we performed is not re-recorded as a user copy.
    private let isSelfWrite: (Int) -> Bool

    var onCapture: ((ClipboardItem) -> Void)?

    init(store: ClipboardStore, isSelfWrite: @escaping (Int) -> Bool) {
        self.store = store
        self.isSelfWrite = isSelfWrite
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start(interval: TimeInterval = 0.25) {
        stop()
        let timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        guard !isSelfWrite(changeCount) else { return }

        // Respect apps that mark content as transient or confidential —
        // password managers use these to stay out of clipboard history.
        let types = pasteboard.types ?? []
        let excluded: Set<String> = [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
        ]
        if types.contains(where: { excluded.contains($0.rawValue) }) { return }

        guard let text = pasteboard.string(forType: .string) else { return }

        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if store.record(text, sourceApp: source), let item = store.item(at: 0) {
            onCapture?(item)
        }
    }
}
